# Generated by Django 3.2.4 on 2021-12-13 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
