# Generated by Django 3.2.4 on 2022-01-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_vissible',
            new_name='is_visible',
        ),
    ]
